version: 2.1

# --------------------------------
# common : base
# --------------------------------

orbs:
  node: circleci/node@5.0.3

# --------------------------------
# env
# --------------------------------

uat_in_app_environment: &uat_in_app_environment
  name: "UAT in app env variables"
  command: |
    echo 'REACT_APP_BLOCK_SYNC_URL=https://blocksync-pandora.ixo.earth' >> .env
    echo 'REACT_APP_IXO_WORLD_ORIGIN=https://uat.ixo.world' >> .env
    echo 'REACT_APP_ASSISTANT_URL=https://bf-ixo-world.development.agents.botfront.cloud' >> .env
    echo 'REACT_APP_KYC_LINK=https://signup.ixo.world' >> .env
    echo 'REACT_APP_IXO_TOKEN_CONTRACT_ADDRESS=0x827a41c26784e0f51081e6d26687bff9c1c667e6' >> .env
    echo 'REACT_APP_PROJECT_REGISTRY_CONTRACT_ADDRESS=0xfe45b990a1dd890adfac13b0a9c77758cc83a862' >> .env
    echo 'REACT_APP_FEE_PER_CLAIM_FEE=0.6' >> .env
    echo 'REACT_APP_FEE_PER_EVALUATION=0.4' >> .env
    echo 'REACT_APP_FEE_OVERHEAD=1.3' >> .env
    echo 'REACT_APP_CHAIN_ID=pandora-6' >> .env
    echo 'REACT_APP_NAME=IXO' >> .env
    echo 'REACT_APP_GAIA_URL=https://testnet.ixo.earth/rest/' >> .env
    echo 'REACT_APP_GOOGLE_API_KEY=AIzaSyDpFiV_PlNEos214wqgOCUpkezMStOyheA' >> .env
    echo 'REACT_APP_PDS_URL=https://cellnode-pandora.ixo.earth/' >> .env
    echo 'REACT_APP_EMBEDLY_KEY=fa2749f731a54587820cf4fcfaa53d30' >> .env
    echo 'REACT_APP_RELAYER_NODE=did:sov:Rmb6Rd1CU6k74FM2xzy6Do' >> .env
    echo 'REACT_APP_ENTITY_VERSION=1.0.0' >> .env
    echo 'REACT_APP_ENTITY_PAGE_VERSION=1.0.0' >> .env
    echo 'REACT_APP_PDS_LOCAL_URL=https://pds_pandora.ixo.world/' >> .env
    echo 'REACT_APP_USE_LOCAL_CELLNODE=false' >> .env
    echo 'REACT_APP_BLOCK_SCAN_URL=https://blockscan-pandora.ixo.earth/' >> .env

# --------------------------------
# jobs
# --------------------------------

jobs:
  test:
    executor:
      name: node/default
      tag: "16.13.1"
    parallelism: 10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: *uat_in_app_environment
      - run:
          command: |
            TEST=$(circleci tests glob src/**/*.test.js | circleci tests split --split-by=timings)
            yarn run test $TEST
          name: Run tests

# --------------------------------
# workflows
# --------------------------------

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - dev
                - impact
  uat_test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - dev
  prod_test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - impact
